name: Build & Push Docker Image on Release

on:
  release:
    types: [published]  # Se déclenche quand une release est publiée

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tags
      run: |
        # Récupère le tag de la release
        TAG=${GITHUB_REF##*/}
        IMAGE="ghcr.io/${{ github.repository_owner }}/docker-ubuntu-cuda-pytorch"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE:$TAG .
        docker push $IMAGE:$TAG
        # Tag latest aussi
        docker tag $IMAGE:$TAG $IMAGE:latest
        docker push $IMAGE:latest
